services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    networks:
      - spring-network
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - spring-network
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongo:27017/todo_app
    depends_on:
      - mongo

  mongo:
    image: mongo:7.0
    container_name: mongodb
    ports:
      - "27017:27017"
    networks:
      - spring-network
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:

networks:
  spring-network:
    driver: bridge
