apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: backend   # Add namespace here
spec:
  selector:
    app: backend
  ports:
  - protocol: TCP
    port: 80          # Exposed service port
    targetPort: 9090  # Matches the backend container port
  type: ClusterIP
