apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: kadhir812/todospring-backend:22
          ports:
            - containerPort: 8080
          env:
            - name: MONGODB_URL
              value: "mongodb://mongodb-service:27017/todo_app"
