apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: todospring-frontend
        image: kadhir812/todospring-frontend:5
        ports:
        - containerPort: 5173
        env:
        - name: BACKEND_URL
          value: "http://backend-service:80"  # Assuming you want to connect to the backend service
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  ports:
  - port: 80
    targetPort: 5173
  selector:
    app: frontend
  type: ClusterIP
