apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: frontend   # Add namespace here
spec:
  ports:
  - port: 80         # Exposed port
    targetPort: 5173  # Container port where the frontend is running
  selector:
    app: frontend
  type: ClusterIP
