apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: kadhir812/todospring-frontend:16
          ports:
            - containerPort: 5173
          env:
            - name: BACKEND_URL
              value: "http://backend:9090"
