apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: frontend  # Ensure backend is in the same namespace or use full service name
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: kadhir812/todospring-frontend:1
          ports:
            - containerPort: 5173
          env:
            - name: BACKEND_URL
              value: "http://backend-service.frontend.svc.cluster.local:8080/api/todos"
