apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongodb-pv
  namespace: backend
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/c/mongodb-datum"  # Maps to C:\mongodb-data on your Windows system
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-pvc
  namespace: backend
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  volumeName: mongodb-pv
