apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pvc
  namespace: mongodb   # Add namespace here
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
