name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  build-and-test-backend:
    runs-on: ubuntu-latest
    container:
      image: kadhir812/maven-abhishek-docker-agent:v2
      options: --user root -v /var/run/docker.sock:/var/run/docker.sock

    env:
      BACKEND_DIR: backend
      SONAR_URL: http://192.168.215.55:9000
      DOCKER_REGISTRY: kadhir812
      BACKEND_IMAGE: kadhir812/todospring-backend:${{ github.run_number }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set Permissions
        run: chmod -R 755 ${{ github.workspace }}

      - name: Build and Test Backend
        run: |
          cd $BACKEND_DIR
          mvn clean package
          mvn test

      - name: SonarQube Analysis
        env:
          SONAR_AUTH_TOKEN: ${{ secrets.SONARQUBE_TOKEN }}
        run: |
          cd $BACKEND_DIR
          mvn sonar:sonar -Dsonar.login=${SONAR_AUTH_TOKEN} -Dsonar.host.url=${SONAR_URL}

      - name: Build and Push Backend Docker Image
        env:
          DOCKER_USER: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKER_PASS: ${{ secrets.DOCKERHUB_PASSWORD }}
        run: |
          cd $BACKEND_DIR
          echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
          docker build -t $BACKEND_IMAGE .
          docker push $BACKEND_IMAGE

  update-k8s-manifests:
    runs-on: ubuntu-latest
    needs: build-and-test-backend

    env:
      K8S_MANIFEST_DIR: k8s-manifests
      BACKEND_IMAGE: kadhir812/todospring-backend:${{ github.run_number }}
      FRONTEND_IMAGE: kadhir812/todospring-frontend:${{ github.run_number }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Configure Git
        run: |
          git config user.email "kadhir555666@gmail.com"
          git config user.name "kadhir812"

      - name: Update Frontend Deployment
        run: |
          cd $K8S_MANIFEST_DIR
          if grep -q 'replaceFrontendImage' frontend-deployment.yaml; then
            sed -i 's|replaceFrontendImage|${FRONTEND_IMAGE}|g' frontend-deployment.yaml
          else
            sed -i 's|image: .*todospring-frontend:.*|image: ${FRONTEND_IMAGE}|g' frontend-deployment.yaml
          fi
          git add frontend-deployment.yaml
          git commit -m "Update frontend image to version ${{ github.run_number }}" || true

      - name: Update Backend Deployment
        run: |
          cd $K8S_MANIFEST_DIR
          if grep -q 'replaceBackendImage' backend-deployment.yaml; then
            sed -i 's|replaceBackendImage|${BACKEND_IMAGE}|g' backend-deployment.yaml
          else
            sed -i 's|image: .*todospring-backend:.*|image: ${BACKEND_IMAGE}|g' backend-deployment.yaml
          fi
          git add backend-deployment.yaml
          git commit -m "Update backend image to version ${{ github.run_number }}" || true

      - name: Push Changes to GitHub
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git push https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git HEAD:master

  cleanup:
    runs-on: ubuntu-latest
    needs: [build-and-test-backend, update-k8s-manifests]
    steps:
      - name: Cleanup Workspace
        run: |
          echo "Cleaning up workspace..."
          rm -rf ${{ github.workspace }}

      - name: Success Notification
        if: success()
        run: echo "Pipeline completed successfully!"

      - name: Failure Notification
        if: failure()
        run: echo "Pipeline failed. Check logs for details."


# Let me know if you want me to tweak anything further! 🚀
